var list = [
  {
    name: "2035是这young",
    artist: "时代少年团",
    url: "./music/2035是这young.m4a",
    cover: "./images/团12.jpg",
  },
  {
    name: "Love the way you lie",
    artist: "左航 /张泽禹",
    url: "./music/Love the way you lie.m4a",
    cover: "./images/左航1.jpg",
  },
  {
    name: "《到底要怎么样》",
    artist: "左航",
    url: "./music/《到底要怎么样》.m4a",
    cover: "./images/左航6.jpg",
  },
  {
    name: "作为怪物 Band Team",
    artist: "马嘉祺/宋亚轩/张真源",
    url: "./music/作为怪物 Band Team.mp3",
    cover: "./images/团11.jpg",
  },
  {
    name: "你我",
    artist: "马嘉祺/宋亚轩/张真源",
    url: "./music/你我.mp3",
    cover: "./images/团2.jpg",
  },
  {
    name: "傻瓜",
    artist: "乌托邦 I • 朱雀-时代少年团",
    url: "./music/傻瓜.m4a",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000004UvCbG14o93g_2.jpg?max_age=2592000",
  },
  {
    name: "全校通报",
    artist: "专辑-舞象之年-时代少年团",
    url: "./music/全校通报mp3.mp3",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000000io1950KoJSv_1.jpg?max_age=2592000",
  },
  {
    name: "剩下的盛夏",
    artist: "马嘉祺/宋亚轩/张真源",
    url: "./music/剩下的盛夏.mp3",
    cover: "./images/团3.jpg",
  },
  {
    name: "只有我一个人觉得？",
    artist: "专辑-舞象之年-时代少年团",
    url: "./music/只有我一个人觉得？.mp3",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000000io1950KoJSv_1.jpg?max_age=2592000",
  },
  {
    name: "哪吒",
    artist: "乌托邦Ⅱ • 哪吒-时代少年团",
    url: "./music/哪吒.m4a",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000003bVz1O0yPOxF_1.jpg?max_age=2592000",
  },
  {
    name: "姐姐真漂亮",
    artist: "专辑-舞象之年-时代少年团",
    url: "./music/姐姐真漂亮.mp3",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000000io1950KoJSv_1.jpg?max_age=2592000",
  },
  {
    name: "庆功酒",
    artist: "左航",
    url: "./music/庆功酒.m4a",
    cover: "./images/左航5.jpg",
  },
  {
    name: "我喜欢你",
    artist: "乌托邦 I • 朱雀-时代少年团",
    url: "./music/我喜欢你.m4a",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000004UvCbG14o93g_2.jpg?max_age=2592000",
  },
  {
    name: "我爱你",
    artist: "马嘉祺",
    url: "./music/我爱你 .mp3",
    cover: "./images/团4.jpg",
  },
  {
    name: "断水流",
    artist: "左航",
    url: "./music/断水流.m4a",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000002BA9py4KbpL4_2.jpg?max_age=2592000",
  },
  {
    name: "有你",
    artist: "专辑-有你-时代少年团",
    url: "./music/有你.m4a",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000003iBcLa2mLPRT_2.jpg?max_age=2592000",
  },
  {
    name: "朱雀",
    artist: "乌托邦 I • 朱雀-时代少年团",
    url: "./music/朱雀.m4a",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000004UvCbG14o93g_2.jpg?max_age=2592000",
  },
  {
    name: "渐暖",
    artist: "专辑-渐暖-时代少年团",
    url: "./music/渐暖.m4a",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000001emlRT0JbjwS_4.jpg?max_age=2592000",
  },
  {
    name: "火力全开",
    artist: "左航/...",
    url: "./music/火力全开.m4a",
    cover: "./images/左航3.jpg",
  },
  {
    name: "爆米花",
    artist: "时代少年团",
    url: "./music/爆米花.mp3",
    cover: "./images/团7.jpg",
  },
  {
    name: "男儿歌",
    artist: "乌托邦Ⅱ • 哪吒-时代少年团",
    url: "./music/男儿歌.m4a",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000003bVz1O0yPOxF_1.jpg?max_age=2592000",
  },
  {
    name: "相遇",
    artist: "专辑-舞象之年-时代少年团",
    url: "./music/相遇.mp3",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000000io1950KoJSv_1.jpg?max_age=2592000",
  },
  {
    name: "破风",
    artist: "时代少年团",
    url: "./music/破风.m4a",
    cover: "./imges/团13.jpg",
  },
  {
    name: "花田错(Live)",
    artist: "左航 /陈天润",
    url: "./music/花田错m4a.m4a",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000002X4tmk3xT53T_1.jpg?max_age=2592000",
  },
  {
    name: "血腥爱情故事",
    artist: "马嘉祺/丁程鑫",
    url: "./music/血腥爱情故事.mp3",
    cover: "./images/团8.jpg",
  },
  {
    name: "要你管",
    artist: "专辑-舞象之年-时代少年团",
    url: "./music/要你管.mp3",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000000io1950KoJSv_1.jpg?max_age=2592000",
  },
  {
    name: "醉",
    artist: "乌托邦Ⅱ • 哪吒-时代少年团",
    url: "./music/醉.m4a",
    cover: "https://y.qq.com/music/photo_new/T002R300x300M000003bVz1O0yPOxF_1.jpg?max_age=2592000",
  },
  {
    name: "顶天立地",
    artist: "朱志鑫/张峻豪/左航/张泽禹",
    url: "./music/顶天立地.m4a",
    cover: "./images/左航4.jpg",
  },
  {
    name: "飘向北方",
    artist: "马嘉祺/严浩翔",
    url: "./music/飘向北方.mp3",
    cover: "./images/团9.jpg",
  },
  {
    name: "黄昏",
    artist: "专辑-",
    url: "./music/黄昏.mp3",
    cover: "https://cdn.jsdelivr.net/gh/nj-lizhi/song@master/audio/cover.png",
  },
  {
    name: "黄昏",
    artist: "专辑-",
    url: "./music/黄昏.mp3",
    cover: "https://cdn.jsdelivr.net/gh/nj-lizhi/song@master/audio/cover.png",
  },
  {
    name: "黄昏",
    artist: "专辑-",
    url: "./music/黄昏.mp3",
    cover: "https://cdn.jsdelivr.net/gh/nj-lizhi/song@master/audio/cover.png",
  },
  {
    name: "黄昏",
    artist: "专辑-",
    url: "./music/黄昏.mp3",
    cover: "https://cdn.jsdelivr.net/gh/nj-lizhi/song@master/audio/cover.png",
  },
  {
    name: "黄昏",
    artist: "专辑-",
    url: "./music/黄昏.mp3",
    cover: "https://cdn.jsdelivr.net/gh/nj-lizhi/song@master/audio/cover.png",
  },
  {
    name: "黄昏",
    artist: "专辑-",
    url: "./music/黄昏.mp3",
    cover: "https://cdn.jsdelivr.net/gh/nj-lizhi/song@master/audio/cover.png",
  },
]
